logLevel = "WARN"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      minVersion = "VersionTLS1"
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/wildcard.pem"
      KeyFile = "/ssl/wildcard.key"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = true
swarmMode = true

## LetsEncrypt
[acme]
email = "acme@example.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true

[acme.httpChallenge]
entryPoint = "http"

[api]
entryPoint = "traefik"
dashboard = true
debug = true
