version: "3.6"

x-global: &global
  image: docker.io/redis:latest
  hostname: "{{.Node.Hostname}}"
  deploy:
    mode: global
  networks:
    hostnet: {}
  volumes:
    - redis:/data
  entrypoint: >
    sh -c "redis-server --port $${PORT}
    --cluster-enabled yes
    --cluster-config-file nodes.conf
    --appendonly yes"

services:
  cache:
    <<: *global
    environmant:
      PORT: 6379

  cache_slave:
    <<: *global
    environmant:
      PORT: 26379
      
  cms:
    <<: *global
    environmant:
      PORT: 6379

  cms_slave:
    <<: *global
    environmant:
      PORT: 26379

networks:
  hostnet:
    external: true
    name: host

volumes:
  redis:
    name: '{{.Service.Name}}'
